name: Clase 2 git hub actions
on: push
jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps: 
    - name: Hola mundo
      run: echo "hola mundo"
  second_job:
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo job 2
        run: echo "job 2"
  
