name: Clase 2 git hub actions
on: push
jobs:
  first_jobs:
    runs-on: ubuntu-latest
    steps: 
    - name: working dir
      run: ls -la 
  second_job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: first_jobs
    runs-on: ubuntu-latest
    steps:
      - name: Hola mundo job 2
        run: echo "job 2"
  
