name: "Hola mundo"

on:
  push: 
    branches: ["main"]
jobs:
 deploy-codigofacilito:
   runs-on: ubuntu-latest
   steps: 
     run: echo "hacemos pull del codigo"
     run: echo "correr migracions"
     run: echo "generar binario"
     run: echo "publicar version"

