name: "Hola mundo"

on:
  push: 
    branches: ["main"]
jobs:
 deploy-codigofacilito:
   runs-on: ubuntu-latest
   steps: 
     - uses: actions/checkout@v4
     - run: echo "hacemos pull del codigo"
     - run: echo "correr migracions"
     - run: echo "generar binario"
     - run: echo "publicar version"

